--CANTIDADES SOLICITADAS
SELECT COUNT(*) AS 'CANTIDAD TIPO LINEA', IF(COUNT(*)=20, 'CUMPLE CON LA CANTIDAD SOLICITADA', 'NO CUMPLE CON LA CANTIDAD SOLICITADA') 'CUMPLE/NO CUMPLE' FROM TIPO_LINEA, 
 
 --REGISTROS ACTIVOS E INACTIVOS
SELECT SUM(IF(ACTIVO='S',1,0)) 'ACTIVO', SUM(IF(ACTIVO='N',1,0)) 'INACTIVOS' FROM TIPO_LINEA
  
--TIPO LINEA 
SELECT * FROM TIPO_LINEA WHERE DESC_LINEA IS NOT NULL AND ID_MARCA IS NOT NULL and ACTIVO IS NOT NULL

--CANTIDADES SOLICITADAS
SELECT COUNT(*) 'CANTIDAD TIPO MARCA', IF(COUNT(*)=5, 'CUMPLE CON LA CANTIDAD SOLICITADA', 'NO CUMPLE CON LA CANTIDAD SOLICITADA') AS 'CUMPLE/NO CUMPLE' FROM TIPO_MARCA

--Se debe generar una consulta que contenga DESC_MARCA, DESC_LINEA y cantidad, para saber cuántas líneas repetidas por marca están almacenadas. (Crear un servicio en Express que devuelva dicha información).
SELECT DESC_MARCA, DESC_LINEA, TM.ID_MARCA, COUNT(*) CANTIDAD FROM TIPO_MARCA TM, TIPO_LINEA TL WHERE TM.ID_MARCA = TL.ID_MARCA GROUP BY TM.ID_MARCA

--TIPO MARCA
SELECT ID_MARCA, DESC_MARCA, IF(ACTIVO='S','ACTIVO','INACTIVO') AS 'ACTIVO' FROM TIPO_MARCA WHERE ACTIVO IS NOT NULL

--MODELO

--MODELO MÁXIMO Y MÍNIMO
SELECT MAX(MODELO) AS 'MODELO MÁXIMO', MIN(MODELO) AS 'MODELO MÍNIMO' FROM VEHICULOS

--RANGO MODELO
SELECT * FROM VEHICULOS WHERE MODELO >= '2018' AND MODELO <= '2021'

--SUMA MODELOS
SELECT SUM(IFNULL(MODELO,0)) 'SUMA MODELOS' FROM VEHICULOS

--PROMEDIO MODELOS 
SELECT AVG(IFNULL(MODELO,0)) 'PROMEDIO MODELOS' FROM VEHICULOS

--CANTIDADES SOLICITADAS
SELECT COUNT(*) AS 'CANTIDAD VEHICULOS', IF(COUNT(*)=30, 'CUMPLE CON LA CANTIDAD SOLICITADA', 'NO CUMPLE CON LA CANTIDAD SOLICITADA') 'CUMPLE/NO CUMPLE' FROM VEHICULOS

  --VEHICULO
SELECT NRO_PLACA,ID_LINEA,MODELO '#ModeloVehiculo: ',
    DATE_FORMAT(FECHA_VEN_SEGURO, '%d/%m/%Y') 'FECHA VENCIMIENTO SEGURO',
    DATE_FORMAT(FECHA_VEN_TECNOMECANICA, '%d/%m/%Y') 'FECHA VENCIMIENTO TECNOMECANICA',
    DATE_FORMAT(FECHA_VEN_CONTRATO, '%d/%m/%Y') 'FECHA VENCIMIENTO CONTRATO' FROM VEHICULOS WHERE ID_LINEA IS NOT NULL AND MODELO IS NOT NULL
  
  --INNER JOIN 
  SELECT NRO_PLACA, MODELO, DESC_LINEA, DESC_MARCA FROM VEHICULOS V INNER JOIN TIPO_LINEA TL ON V.ID_LINEA=TL.ID_LINEA INNER JOIN TIPO_MARCA TM ON TL.ID_MARCA = TM.ID_MARCA

  --LEFT JOIN 
SELECT NRO_PLACA, MODELO, DESC_LINEA, DESC_MARCA FROM VEHICULOS V LEFT JOIN TIPO_LINEA TL ON V.ID_LINEA=TL.ID_LINEA LEFT JOIN TIPO_MARCA TM ON TL.ID_MARCA = TM.ID_MARCA

  --RANGO DE FECHA
SELECT * FROM VEHICULOS WHERE FECHA_VEN_SEGURO >= '2015-01-01' AND FECHA_VEN_SEGURO <= '2019-01-01'

  --Crear una consulta única que tenga las siguientes columnas: NRO_PLACA, MODELO, DESC_LINEA, DESC_MARCA, traer todos los registros que coincidan en todas las tablas.
SELECT NRO_PLACA, MODELO, DESC_MARCA, DESC_LINEA, TL.ACTIVO, TM.ACTIVO FROM VEHICULOS V, TIPO_MARCA TM, TIPO_LINEA TL WHERE TM.ID_MARCA=TL.ID_MARCA AND TL.ID_LINEA=V.ID_LINEA

  --Crear una consulta única que tenga las siguientes columnas: NRO_PLACA, MODELO, DESC_LINEA, DESC_MARCA; traer todos los registros que coincidan en todas las tablas y que se encuentren en estado S. (Crear un servicio en Express).
SELECT NRO_PLACA, MODELO, DESC_MARCA, DESC_LINEA, TL.ACTIVO 'TIPO LINEA ACTIVO', TM.ACTIVO 'TIPO MARCA ACTIVO' FROM VEHICULOS V, TIPO_MARCA TM, TIPO_LINEA TL WHERE TM.ID_MARCA=TL.ID_MARCA AND TL.ID_LINEA=V.ID_LINEA AND TL.ACTIVO='S' AND TM.ACTIVO='S'
